document.querySelector(".hamb").addEventListener('click', function(e) {
    document.getElementById('one').classList.toggle('oneClick')
    document.getElementById('two').classList.toggle('twoClick')
    document.getElementById('trhee').classList.toggle('trheeClick')
    document.querySelector('.menu').classList.toggle('menuClick')
    document.getElementById('img-1').classList.toggle('blurr')
    document.getElementById('img-2').classList.toggle('blurr')
    document.getElementById('img-3').classList.toggle('blurr')
    document.getElementById('img-4').classList.toggle('blurr')
})